INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (1, 'Pizza', 'Tomato');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (1, 'Pizza', 'Cheese');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (1, 'Pizza', 'Bread');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (2, 'Pesto Pasta', 'Penne');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (2, 'Pesto Pasta', 'Tomato Sauce');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (2, 'Pesto Pasta', 'Pesto');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (2, 'Pesto Pasta', 'Garlic');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (2, 'Pesto Pasta', 'Olive Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (2, 'Pesto Pasta', 'Cheese');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (3, 'Shrimp Fried Rice', 'Shrimp');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (3, 'Shrimp Fried Rice', 'Egg');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (3, 'Shrimp Fried Rice', 'Ginger');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (3, 'Shrimp Fried Rice', 'Garlic');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (3, 'Shrimp Fried Rice', 'Scallions');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (3, 'Shrimp Fried Rice', 'Rice');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (3, 'Shrimp Fried Rice', 'Soy Sauce');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (4, 'Creamy Homemade Baked Mac and Cheese', 'Elbow Pasta');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (4, 'Creamy Homemade Baked Mac and Cheese', 'Unsalted Butter');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (4, 'Creamy Homemade Baked Mac and Cheese', 'Flour');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (4, 'Creamy Homemade Baked Mac and Cheese', 'All Purpose Flour');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (4, 'Creamy Homemade Baked Mac and Cheese', 'Whole Milk');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (4, 'Creamy Homemade Baked Mac and Cheese', 'Milk');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (4, 'Creamy Homemade Baked Mac and Cheese', 'Half and Half');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (4, 'Creamy Homemade Baked Mac and Cheese', 'Cheddar Cheese');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (4, 'Creamy Homemade Baked Mac and Cheese', 'Gruyere Cheese');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (4, 'Creamy Homemade Baked Mac and Cheese', 'Paprika');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (5, 'Oven Roasted Potato ''Fries''', 'Potato');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (5, 'Oven Roasted Potato ''Fries''', 'Olive Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (5, 'Oven Roasted Potato ''Fries''', 'Paprika');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (11, 'Roasted Salmon Glazed With Brown Sugar and Mustard', 'Salmon');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (11, 'Roasted Salmon Glazed With Brown Sugar and Mustard', 'Brown Sugar');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (11, 'Roasted Salmon Glazed With Brown Sugar and Mustard', 'Dijon Mustard');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (12, 'Spaghetti al Limone', 'Lemon');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (12, 'Spaghetti al Limone', 'White wine');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (12, 'Spaghetti al Limone', 'Heavy cream');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (12, 'Spaghetti al Limone', 'Spaghetti');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (12, 'Spaghetti al Limone', 'Unsalted Butter');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (12, 'Spaghetti al Limone', 'Parmesan cheese');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (12, 'Spaghetti al Limone', 'Olive Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (12, 'Spaghetti al Limone', 'Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (12, 'Spaghetti al Limone', 'Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (13, 'Spinach and Red Pepper Frittata', 'Spinach');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (13, 'Spinach and Red Pepper Frittata', 'Olive Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (13, 'Spinach and Red Pepper Frittata', 'Red Peppers');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (13, 'Spinach and Red Pepper Frittata', 'Garlic');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (13, 'Spinach and Red Pepper Frittata', 'Marjoram leaves');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (13, 'Spinach and Red Pepper Frittata', 'Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (13, 'Spinach and Red Pepper Frittata', 'Egg');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (13, 'Spinach and Red Pepper Frittata', 'Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (13, 'Spinach and Red Pepper Frittata', 'Milk');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (14, 'Sweet Potato Meringue Pie', 'Egg');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (14, 'Sweet Potato Meringue Pie', 'Brown Sugar');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (14, 'Sweet Potato Meringue Pie', 'Pie Crust');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (14, 'Sweet Potato Meringue Pie', 'Sugar');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (14, 'Sweet Potato Meringue Pie', 'Vanilla extract');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (14, 'Sweet Potato Meringue Pie', 'Unsalted Butter');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (14, 'Sweet Potato Meringue Pie', 'Sweet Potatoes');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (14, 'Sweet Potato Meringue Pie', 'Cinnamon');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (14, 'Sweet Potato Meringue Pie', 'Ginger');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (14, 'Sweet Potato Meringue Pie', 'Nutmeg');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (14, 'Sweet Potato Meringue Pie', 'Heavy cream');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (14, 'Sweet Potato Meringue Pie', 'Egg');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (29, 'Buttermilk Pancakes', 'All Purpose Flour');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (29, 'Buttermilk Pancakes', 'Sugar');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (29, 'Buttermilk Pancakes', 'Baking Powder');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (29, 'Buttermilk Pancakes', 'Baking Soda');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (29, 'Buttermilk Pancakes', 'Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (29, 'Buttermilk Pancakes', 'Buttermilk');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (29, 'Buttermilk Pancakes', 'Milk');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (29, 'Buttermilk Pancakes', 'Egg');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (31, 'French Toast', 'Egg');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (31, 'French Toast', 'Milk');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (31, 'French Toast', 'Cinnamon');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (31, 'French Toast', 'Bread');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (32, 'Ground Beef Gyros', 'Plain Yogurt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (32, 'Ground Beef Gyros', 'Cucumber');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (32, 'Ground Beef Gyros', 'Onion');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (32, 'Ground Beef Gyros', 'Garlic');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (32, 'Ground Beef Gyros', 'Sugar');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (32, 'Ground Beef Gyros', 'Ground Beef');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (32, 'Ground Beef Gyros', 'Oregano');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (32, 'Ground Beef Gyros', 'Garlic Powder');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (32, 'Ground Beef Gyros', 'Onion Powder');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (32, 'Ground Beef Gyros', 'Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (32, 'Ground Beef Gyros', 'Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (32, 'Ground Beef Gyros', 'Pita Bread');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (33, 'Mac & Cheese', 'Macaroni');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (33, 'Mac & Cheese', 'Salted Butter');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (33, 'Mac & Cheese', 'All Purpose Flour');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (33, 'Mac & Cheese', 'Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (33, 'Mac & Cheese', 'Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (33, 'Mac & Cheese', 'Milk');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (33, 'Mac & Cheese', 'Cheddar Cheese');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (34, 'Ginger Bread Cookies', 'All Purpose Flour');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (34, 'Ginger Bread Cookies', 'Baking Soda');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (34, 'Ginger Bread Cookies', 'Baking Powder');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (34, 'Ginger Bread Cookies', 'Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (34, 'Ginger Bread Cookies', 'Ginger');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (34, 'Ginger Bread Cookies', 'Cinnamon');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (34, 'Ginger Bread Cookies', 'Ground Cloves');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (34, 'Ginger Bread Cookies', 'Unsalted Butter');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (34, 'Ginger Bread Cookies', 'Brown Sugar');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (34, 'Ginger Bread Cookies', 'Egg');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (34, 'Ginger Bread Cookies', 'Molasses');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (34, 'Ginger Bread Cookies', 'Vanilla extract');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (34, 'Ginger Bread Cookies', 'Lemon Zest');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (35, 'Italian Meatballs', 'Ground Beef');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (35, 'Italian Meatballs', 'Egg');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (35, 'Italian Meatballs', 'Milk');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (35, 'Italian Meatballs', 'Breadcrumbs');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (35, 'Italian Meatballs', 'Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (35, 'Italian Meatballs', 'Parsley');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (35, 'Italian Meatballs', 'Garlic Powder');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (35, 'Italian Meatballs', 'Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (35, 'Italian Meatballs', 'Cheese');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (36, 'Fried Rice', 'Onion');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (36, 'Fried Rice', 'Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (36, 'Fried Rice', 'Egg');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (36, 'Fried Rice', 'Soy Sauce');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (36, 'Fried Rice', 'Sesame Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (36, 'Fried Rice', 'Chicken');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (36, 'Fried Rice', 'Carrot');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (36, 'Fried Rice', 'Peas');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (36, 'Fried Rice', 'Rice');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (36, 'Fried Rice', 'Green Onions');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (36, 'Fried Rice', 'Bean Sprouts');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (37, 'Chili', 'Ground Beef');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (37, 'Chili', 'Onion');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (37, 'Chili', 'Green Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (37, 'Chili', 'Jalapeno');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (37, 'Chili', 'Tomato');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (37, 'Chili', 'Cumin');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (37, 'Chili', 'Chili Powder');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (37, 'Chili', 'Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (37, 'Chili', 'Cayenne Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (37, 'Chili', 'Paprika');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (37, 'Chili', 'Kidney Beans');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (37, 'Chili', 'Black Beans');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (37, 'Chili', 'Water');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (38, 'Chicken Parmesan', 'Chicken');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (38, 'Chicken Parmesan', 'Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (38, 'Chicken Parmesan', 'Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (38, 'Chicken Parmesan', 'Breadcrumbs');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (38, 'Chicken Parmesan', 'Egg');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (38, 'Chicken Parmesan', 'Tomato Sauce');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (38, 'Chicken Parmesan', 'Salted Butter');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (38, 'Chicken Parmesan', 'Cheese');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (38, 'Chicken Parmesan', 'Parmesan cheese');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (38, 'Chicken Parmesan', 'Spaghetti');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (38, 'Chicken Parmesan', 'Parsley');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (39, 'Brownies', 'Vegetable Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (39, 'Brownies', 'Sugar');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (39, 'Brownies', 'Vanilla extract');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (39, 'Brownies', 'Egg');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (39, 'Brownies', 'Baking Powder');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (39, 'Brownies', 'Cocoa Powder');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (39, 'Brownies', 'Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (39, 'Brownies', 'Flour');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (40, 'Chicken Noodle Soup', 'Salted Butter');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (40, 'Chicken Noodle Soup', 'Celery');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (40, 'Chicken Noodle Soup', 'Carrot');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (40, 'Chicken Noodle Soup', 'Onion');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (40, 'Chicken Noodle Soup', 'Thyme');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (40, 'Chicken Noodle Soup', 'Poultry Seasoning');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (40, 'Chicken Noodle Soup', 'Chicken Broth');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (40, 'Chicken Noodle Soup', 'Chicken Bouillon');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (40, 'Chicken Noodle Soup', 'Egg Noodle');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (40, 'Chicken Noodle Soup', 'Chicken');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (40, 'Chicken Noodle Soup', 'Parsley');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (41, 'Chicken Wings', 'Flour');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (41, 'Chicken Wings', 'Paprika');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (41, 'Chicken Wings', 'Garlic Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (41, 'Chicken Wings', 'Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (41, 'Chicken Wings', 'Cayenne Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (41, 'Chicken Wings', 'Salted Butter');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (41, 'Chicken Wings', 'Chicken');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (42, 'Baked Salmon', 'Garlic');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (42, 'Baked Salmon', 'Light Olive Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (42, 'Baked Salmon', 'Basil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (42, 'Baked Salmon', 'Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (42, 'Baked Salmon', 'Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (42, 'Baked Salmon', 'Lemon juice');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (42, 'Baked Salmon', 'Parsley');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (42, 'Baked Salmon', 'Salmon');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (43, 'Garlic Shrimp', 'Shrimp');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (43, 'Garlic Shrimp', 'Olive Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (43, 'Garlic Shrimp', 'Garlic');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (43, 'Garlic Shrimp', 'Red Pepper Flakes');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (43, 'Garlic Shrimp', 'Steak Seasoning');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (43, 'Garlic Shrimp', 'Lemon Zest');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (43, 'Garlic Shrimp', 'Lemon juice');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (43, 'Garlic Shrimp', 'Parsley');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (44, 'Fried Chicken', 'Chicken');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (44, 'Fried Chicken', 'Egg');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (44, 'Fried Chicken', 'Water');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (44, 'Fried Chicken', 'Hot Sauce');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (44, 'Fried Chicken', 'Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (44, 'Fried Chicken', 'Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (44, 'Fried Chicken', 'Garlic Powder');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (44, 'Fried Chicken', 'All Purpose Flour');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (44, 'Fried Chicken', 'Baking Powder');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (45, 'Beef Stew', 'Beef Stew Meat');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (45, 'Beef Stew', 'Flour');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (45, 'Beef Stew', 'Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (45, 'Beef Stew', 'Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (45, 'Beef Stew', 'Vegetable Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (45, 'Beef Stew', 'Onion');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (45, 'Beef Stew', 'Carrot');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (45, 'Beef Stew', 'Celery');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (45, 'Beef Stew', 'Parsley');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (45, 'Beef Stew', 'Thyme');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (45, 'Beef Stew', 'Beef Broth');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (45, 'Beef Stew', 'Potato');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (46, 'Sesame Chicken', 'Chicken');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (46, 'Sesame Chicken', 'Honey');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (46, 'Sesame Chicken', 'Soy Sauce');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (46, 'Sesame Chicken', 'Water');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (46, 'Sesame Chicken', 'Cornstarch');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (46, 'Sesame Chicken', 'Ginger');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (46, 'Sesame Chicken', 'Red Pepper Flakes');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (46, 'Sesame Chicken', 'Sesame Seeds');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (47, 'Greek Potatoes', 'Potato');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (47, 'Greek Potatoes', 'Garlic');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (47, 'Greek Potatoes', 'Olive Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (47, 'Greek Potatoes', 'Water');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (47, 'Greek Potatoes', 'Oregano');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (47, 'Greek Potatoes', 'Lemon');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (47, 'Greek Potatoes', 'Sea Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (47, 'Greek Potatoes', 'Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (48, 'Sweet Potato Pie', 'Salted Butter');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (48, 'Sweet Potato Pie', 'Sugar');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (48, 'Sweet Potato Pie', 'Egg');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (48, 'Sweet Potato Pie', 'Evaporated Milk');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (48, 'Sweet Potato Pie', 'Mashed Potatoes');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (48, 'Sweet Potato Pie', 'Vanilla extract');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (48, 'Sweet Potato Pie', 'Cinnamon');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (48, 'Sweet Potato Pie', 'Nutmeg');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (48, 'Sweet Potato Pie', 'Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (48, 'Sweet Potato Pie', 'Pie Crust');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (49, 'Bacardi Rum Cake', 'Pecans');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (49, 'Bacardi Rum Cake', 'Cake Mix');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (49, 'Bacardi Rum Cake', 'Vanilla Pudding');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (49, 'Bacardi Rum Cake', 'Egg');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (49, 'Bacardi Rum Cake', 'Water');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (49, 'Bacardi Rum Cake', 'Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (49, 'Bacardi Rum Cake', 'Rum');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (49, 'Bacardi Rum Cake', 'Salted Butter');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (49, 'Bacardi Rum Cake', 'Sugar');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (50, 'Sloppy Joes', 'Hamburger');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (50, 'Sloppy Joes', 'Onion');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (50, 'Sloppy Joes', 'Tomato Sauce');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (50, 'Sloppy Joes', 'Worcestershire Sauce');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (50, 'Sloppy Joes', 'Brown Sugar');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (50, 'Sloppy Joes', 'Vinegar');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (50, 'Sloppy Joes', 'Catsup');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (50, 'Sloppy Joes', 'Chili Powder');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (50, 'Sloppy Joes', 'Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (50, 'Sloppy Joes', 'Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (50, 'Sloppy Joes', 'Yellow Mustard');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (51, 'Lemon Baked Cod', 'Cod Fish Fillet');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (51, 'Lemon Baked Cod', 'Salted Butter');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (51, 'Lemon Baked Cod', 'Lemon juice');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (51, 'Lemon Baked Cod', 'All Purpose Flour');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (51, 'Lemon Baked Cod', 'Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (51, 'Lemon Baked Cod', 'White Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (51, 'Lemon Baked Cod', 'Paprika');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (52, 'Corn on the Cob', 'Corn');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (52, 'Corn on the Cob', 'Salted Butter');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (53, 'Flat Iron Steak', 'Flat Iron Steak');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (53, 'Flat Iron Steak', 'Italian Dressing');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (53, 'Flat Iron Steak', 'Sour Cream');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (53, 'Flat Iron Steak', 'Parmesan cheese');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (53, 'Flat Iron Steak', 'Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (53, 'Flat Iron Steak', 'Sea Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (53, 'Flat Iron Steak', 'Garlic');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (53, 'Flat Iron Steak', 'Onion');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (54, 'Teriyaki Pork Chops', 'Pork Chops');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (54, 'Teriyaki Pork Chops', 'Orange Juice');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (54, 'Teriyaki Pork Chops', 'Soy Sauce');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (54, 'Teriyaki Pork Chops', 'Water');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (54, 'Teriyaki Pork Chops', 'Garlic');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (54, 'Teriyaki Pork Chops', 'Honey');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (54, 'Teriyaki Pork Chops', 'Ginger');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (55, 'French Bread', 'Water');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (55, 'French Bread', 'Active Dry Yeast');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (55, 'French Bread', 'Vegetable Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (55, 'French Bread', 'Sugar');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (55, 'French Bread', 'Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (55, 'French Bread', 'Flour');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (56, 'Marbled Brownies', 'Brownie Mix');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (56, 'Marbled Brownies', 'Egg');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (56, 'Marbled Brownies', 'Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (56, 'Marbled Brownies', 'Cream Cheese');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (56, 'Marbled Brownies', 'Salted Butter');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (56, 'Marbled Brownies', 'Sugar');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (56, 'Marbled Brownies', 'Flour');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (56, 'Marbled Brownies', 'Vanilla extract');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (56, 'Marbled Brownies', 'Cocoa Powder');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (56, 'Marbled Brownies', 'Powdered Sugar');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (56, 'Marbled Brownies', 'Milk');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (57, 'Cookies N Cream Fudge', 'Sugar');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (57, 'Cookies N Cream Fudge', 'Salted Butter');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (57, 'Cookies N Cream Fudge', 'Evaporated Milk');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (57, 'Cookies N Cream Fudge', 'Marshmallow Creme');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (57, 'Cookies N Cream Fudge', 'Almond Bark');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (57, 'Cookies N Cream Fudge', 'Vanilla extract');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (57, 'Cookies N Cream Fudge', 'Oreos');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (58, 'Corned Beef and Cabbage', 'Water');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (58, 'Corned Beef and Cabbage', 'Apple Cider Vinegar');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (58, 'Corned Beef and Cabbage', 'Sugar');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (58, 'Corned Beef and Cabbage', 'Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (58, 'Corned Beef and Cabbage', 'Onion');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (58, 'Corned Beef and Cabbage', 'Corned Beef Brisket');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (58, 'Corned Beef and Cabbage', 'Potato');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (58, 'Corned Beef and Cabbage', 'Cabbage');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (58, 'Corned Beef and Cabbage', 'Carrot');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (59, 'Sweet Potato Chips', 'Sweet Potatoes');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (59, 'Sweet Potato Chips', 'Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (59, 'Sweet Potato Chips', 'Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (60, 'Tofu Stir Fry', 'Teriyaki Sauce');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (60, 'Tofu Stir Fry', 'Tofu');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (60, 'Tofu Stir Fry', 'Garlic');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (60, 'Tofu Stir Fry', 'Peanut Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (60, 'Tofu Stir Fry', 'Mixed Vegetables');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (61, 'Shrimp Fried Rice', 'Vegetable Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (61, 'Shrimp Fried Rice', 'Garlic');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (61, 'Shrimp Fried Rice', 'Carrot');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (61, 'Shrimp Fried Rice', 'Green Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (61, 'Shrimp Fried Rice', 'Shrimp');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (61, 'Shrimp Fried Rice', 'Rice');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (61, 'Shrimp Fried Rice', 'Peas');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (61, 'Shrimp Fried Rice', 'Soy Sauce');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (61, 'Shrimp Fried Rice', 'Sesame Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (61, 'Shrimp Fried Rice', 'Egg');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (61, 'Shrimp Fried Rice', 'Green Onions');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (61, 'Shrimp Fried Rice', 'Hot Sauce');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (62, 'Shrimp and Broccoli Fettuccini', 'Fettuccini');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (62, 'Shrimp and Broccoli Fettuccini', 'Extra-virgin Olive Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (62, 'Shrimp and Broccoli Fettuccini', 'Broccoli');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (62, 'Shrimp and Broccoli Fettuccini', 'Salted Butter');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (62, 'Shrimp and Broccoli Fettuccini', 'Garlic');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (62, 'Shrimp and Broccoli Fettuccini', 'Chicken Broth');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (62, 'Shrimp and Broccoli Fettuccini', 'Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (62, 'Shrimp and Broccoli Fettuccini', 'Shrimp');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (62, 'Shrimp and Broccoli Fettuccini', 'Tomato Sauce');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (62, 'Shrimp and Broccoli Fettuccini', 'Heavy cream');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (62, 'Shrimp and Broccoli Fettuccini', 'Parsley');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (63, 'Coconut Shrimp with Spicy Honey', 'Rice');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (63, 'Coconut Shrimp with Spicy Honey', 'Honey');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (63, 'Coconut Shrimp with Spicy Honey', 'Lemon');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (63, 'Coconut Shrimp with Spicy Honey', 'Cayenne Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (63, 'Coconut Shrimp with Spicy Honey', 'Shrimp');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (63, 'Coconut Shrimp with Spicy Honey', 'Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (63, 'Coconut Shrimp with Spicy Honey', 'All Purpose Flour');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (63, 'Coconut Shrimp with Spicy Honey', 'Egg');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (63, 'Coconut Shrimp with Spicy Honey', 'Breadcrumbs');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (63, 'Coconut Shrimp with Spicy Honey', 'Unsweetened Shredded Coconut');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (63, 'Coconut Shrimp with Spicy Honey', 'Vegetable Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (63, 'Coconut Shrimp with Spicy Honey', 'Green Onions');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (64, 'Corn Bread Chili Pie', 'Olive Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (64, 'Corn Bread Chili Pie', 'Onion');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (64, 'Corn Bread Chili Pie', 'Garlic');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (64, 'Corn Bread Chili Pie', 'Ground Beef');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (64, 'Corn Bread Chili Pie', 'Ground Pork');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (64, 'Corn Bread Chili Pie', 'Chili Powder');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (64, 'Corn Bread Chili Pie', 'Tomato');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (64, 'Corn Bread Chili Pie', 'Tomato Paste');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (64, 'Corn Bread Chili Pie', 'Chicken Broth');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (64, 'Corn Bread Chili Pie', 'Muffin Mix');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (64, 'Corn Bread Chili Pie', 'Egg');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (64, 'Corn Bread Chili Pie', 'Milk');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (64, 'Corn Bread Chili Pie', 'Corn');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (64, 'Corn Bread Chili Pie', 'Cheddar Cheese');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (64, 'Corn Bread Chili Pie', 'Kidney Beans');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (64, 'Corn Bread Chili Pie', 'Salsa');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (64, 'Corn Bread Chili Pie', 'Green Onions');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (64, 'Corn Bread Chili Pie', 'Sour Cream');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (65, 'Bolognese Sauce', 'Extra-virgin Olive Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (65, 'Bolognese Sauce', 'Onion');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (65, 'Bolognese Sauce', 'Carrot');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (65, 'Bolognese Sauce', 'Celery');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (65, 'Bolognese Sauce', 'Ground Beef');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (65, 'Bolognese Sauce', 'Garlic');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (65, 'Bolognese Sauce', 'White wine');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (65, 'Bolognese Sauce', 'Tomato');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (65, 'Bolognese Sauce', 'Beef Broth');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (65, 'Bolognese Sauce', 'Tomato Paste');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (65, 'Bolognese Sauce', 'Bay Leaves');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (65, 'Bolognese Sauce', 'Whole Milk');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (65, 'Bolognese Sauce', 'Kosher Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (65, 'Bolognese Sauce', 'Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (66, 'Beef Stroganoff', 'Egg Noodle');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (66, 'Beef Stroganoff', 'Salted Butter');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (66, 'Beef Stroganoff', 'Vegetable Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (66, 'Beef Stroganoff', 'Beef Chuck Roast');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (66, 'Beef Stroganoff', 'Kosher Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (66, 'Beef Stroganoff', 'Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (66, 'Beef Stroganoff', 'Extra-virgin Olive Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (66, 'Beef Stroganoff', 'Mushrooms');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (66, 'Beef Stroganoff', 'Onion');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (66, 'Beef Stroganoff', 'Garlic');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (66, 'Beef Stroganoff', 'Thyme');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (66, 'Beef Stroganoff', 'Tomato Paste');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (66, 'Beef Stroganoff', 'Beef Broth');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (66, 'Beef Stroganoff', 'Dijon Mustard');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (66, 'Beef Stroganoff', 'Worcestershire Sauce');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (66, 'Beef Stroganoff', 'Cornstarch');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (66, 'Beef Stroganoff', 'Sour Cream');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (66, 'Beef Stroganoff', 'Parsley');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (67, 'Reuben Sandwich', 'Rye Bread');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (67, 'Reuben Sandwich', 'Salted Butter');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (67, 'Reuben Sandwich', 'Russian Dressing');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (67, 'Reuben Sandwich', 'Swiss Cheese');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (67, 'Reuben Sandwich', 'Corned Beef Brisket');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (67, 'Reuben Sandwich', 'Sauerkraut');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (68, 'Chicken Chow Mein', 'Chow Mein Noodles');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (68, 'Chicken Chow Mein', 'Sesame Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (68, 'Chicken Chow Mein', 'Chicken');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (68, 'Chicken Chow Mein', 'Kosher Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (68, 'Chicken Chow Mein', 'Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (68, 'Chicken Chow Mein', 'Garlic');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (68, 'Chicken Chow Mein', 'Ginger');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (68, 'Chicken Chow Mein', 'Carrot');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (68, 'Chicken Chow Mein', 'Cabbage');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (68, 'Chicken Chow Mein', 'Chicken Broth');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (68, 'Chicken Chow Mein', 'Soy Sauce');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (68, 'Chicken Chow Mein', 'Oyster Sauce');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (68, 'Chicken Chow Mein', 'Green Onions');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (68, 'Chicken Chow Mein', 'Sesame Seeds');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (69, 'Greek Salad', 'Tomato');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (69, 'Greek Salad', 'Cucumber');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (69, 'Greek Salad', 'Kalamata Olives');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (69, 'Greek Salad', 'Red Onion');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (69, 'Greek Salad', 'Feta Cheese');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (69, 'Greek Salad', 'Red Wine Vinegar');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (69, 'Greek Salad', 'Lemon juice');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (69, 'Greek Salad', 'Oregano');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (69, 'Greek Salad', 'Kosher Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (69, 'Greek Salad', 'Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (69, 'Greek Salad', 'Extra-virgin Olive Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (70, 'Chimichurri Grilled Steak', 'Cilantro');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (70, 'Chimichurri Grilled Steak', 'Chives');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (70, 'Chimichurri Grilled Steak', 'Lime');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (70, 'Chimichurri Grilled Steak', 'Extra-virgin Olive Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (70, 'Chimichurri Grilled Steak', 'Red Pepper Flakes');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (70, 'Chimichurri Grilled Steak', 'Kosher Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (70, 'Chimichurri Grilled Steak', 'Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (70, 'Chimichurri Grilled Steak', 'Skirt Steak');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (70, 'Chimichurri Grilled Steak', 'Garlic');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (70, 'Chimichurri Grilled Steak', 'Lemon juice');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (70, 'Chimichurri Grilled Steak', 'Asparagus');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (71, 'Swedish Meatballs and Mashed Potatoes', 'Potato');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (71, 'Swedish Meatballs and Mashed Potatoes', 'Salted Butter');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (71, 'Swedish Meatballs and Mashed Potatoes', 'Heavy cream');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (71, 'Swedish Meatballs and Mashed Potatoes', 'Kosher Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (71, 'Swedish Meatballs and Mashed Potatoes', 'Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (71, 'Swedish Meatballs and Mashed Potatoes', 'White Bread');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (71, 'Swedish Meatballs and Mashed Potatoes', 'Whole Milk');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (71, 'Swedish Meatballs and Mashed Potatoes', 'Onion');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (71, 'Swedish Meatballs and Mashed Potatoes', 'Garlic');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (71, 'Swedish Meatballs and Mashed Potatoes', 'Ground Beef');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (71, 'Swedish Meatballs and Mashed Potatoes', 'Ground Pork');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (71, 'Swedish Meatballs and Mashed Potatoes', 'Egg');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (71, 'Swedish Meatballs and Mashed Potatoes', 'Allspice');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (71, 'Swedish Meatballs and Mashed Potatoes', 'Nutmeg');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (71, 'Swedish Meatballs and Mashed Potatoes', 'All Purpose Flour');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (71, 'Swedish Meatballs and Mashed Potatoes', 'Beef Broth');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (71, 'Swedish Meatballs and Mashed Potatoes', 'Chives');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (73, 'Steak Frites', 'Canola Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (73, 'Steak Frites', 'Potato');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (73, 'Steak Frites', 'Extra-virgin Olive Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (73, 'Steak Frites', 'Salted Butter');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (73, 'Steak Frites', 'New York Strip Steak');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (73, 'Steak Frites', 'Kosher Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (73, 'Steak Frites', 'Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (73, 'Steak Frites', 'Sea Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (73, 'Steak Frites', 'Parsley');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (74, 'Mediterranean Salad with Lemon-Herb Vinaigrette', 'Pita Bread');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (74, 'Mediterranean Salad with Lemon-Herb Vinaigrette', 'Extra-virgin Olive Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (74, 'Mediterranean Salad with Lemon-Herb Vinaigrette', 'Mint Leaves');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (74, 'Mediterranean Salad with Lemon-Herb Vinaigrette', 'Parsley');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (74, 'Mediterranean Salad with Lemon-Herb Vinaigrette', 'Basil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (74, 'Mediterranean Salad with Lemon-Herb Vinaigrette', 'Lemon juice');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (74, 'Mediterranean Salad with Lemon-Herb Vinaigrette', 'Sugar');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (74, 'Mediterranean Salad with Lemon-Herb Vinaigrette', 'Kosher Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (74, 'Mediterranean Salad with Lemon-Herb Vinaigrette', 'Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (74, 'Mediterranean Salad with Lemon-Herb Vinaigrette', 'Tomato');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (74, 'Mediterranean Salad with Lemon-Herb Vinaigrette', 'Cucumber');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (74, 'Mediterranean Salad with Lemon-Herb Vinaigrette', 'Feta Cheese');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (74, 'Mediterranean Salad with Lemon-Herb Vinaigrette', 'Kalamata Olives');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (75, 'Steak Salad', 'Squash');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (75, 'Steak Salad', 'Extra-virgin Olive Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (75, 'Steak Salad', 'Kosher Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (75, 'Steak Salad', 'Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (75, 'Steak Salad', 'Thyme');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (75, 'Steak Salad', 'Flank Steak');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (75, 'Steak Salad', 'Sherry Vinegar');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (75, 'Steak Salad', 'Honey');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (75, 'Steak Salad', 'Spinach');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (75, 'Steak Salad', 'Blue Cheese');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (76, 'Sesame Ginger Salmon Salad', 'Soy Sauce');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (76, 'Sesame Ginger Salmon Salad', 'Ginger');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (76, 'Sesame Ginger Salmon Salad', 'Garlic');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (76, 'Sesame Ginger Salmon Salad', 'Green Onions');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (76, 'Sesame Ginger Salmon Salad', 'Sesame Seeds');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (76, 'Sesame Ginger Salmon Salad', 'Vegetable Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (76, 'Sesame Ginger Salmon Salad', 'White Vinegar');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (76, 'Sesame Ginger Salmon Salad', 'Honey');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (76, 'Sesame Ginger Salmon Salad', 'Sesame Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (76, 'Sesame Ginger Salmon Salad', 'Wonton Wrappers');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (76, 'Sesame Ginger Salmon Salad', 'Kosher Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (76, 'Sesame Ginger Salmon Salad', 'Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (76, 'Sesame Ginger Salmon Salad', 'Salmon');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (76, 'Sesame Ginger Salmon Salad', 'Extra-virgin Olive Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (76, 'Sesame Ginger Salmon Salad', 'Mixed Greens');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (76, 'Sesame Ginger Salmon Salad', 'Carrot');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (77, 'Peppermint Bark', 'Semisweet Chocolate');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (77, 'Peppermint Bark', 'White Chocolate');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (77, 'Peppermint Bark', 'Peppermint Extract');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (77, 'Peppermint Bark', 'Candy Canes');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (78, 'Baked Swordfish Steak', 'Extra-virgin Olive Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (78, 'Baked Swordfish Steak', 'Swordfish Steaks');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (78, 'Baked Swordfish Steak', 'Kosher Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (78, 'Baked Swordfish Steak', 'Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (78, 'Baked Swordfish Steak', 'Tomato');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (78, 'Baked Swordfish Steak', 'Red Onion');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (78, 'Baked Swordfish Steak', 'Basil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (78, 'Baked Swordfish Steak', 'Lemon juice');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (79, 'Shrimp Fajitas', 'Extra-virgin Olive Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (79, 'Shrimp Fajitas', 'Lime');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (79, 'Shrimp Fajitas', 'Chili Powder');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (79, 'Shrimp Fajitas', 'Shrimp');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (79, 'Shrimp Fajitas', 'Vegetable Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (79, 'Shrimp Fajitas', 'Red Bell Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (79, 'Shrimp Fajitas', 'Onion');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (79, 'Shrimp Fajitas', 'Kosher Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (79, 'Shrimp Fajitas', 'Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (79, 'Shrimp Fajitas', 'Jalapeno');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (79, 'Shrimp Fajitas', 'Garlic');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (79, 'Shrimp Fajitas', 'Corn Tortillas');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (79, 'Shrimp Fajitas', 'Cilantro');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (79, 'Shrimp Fajitas', 'Cotija');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (80, 'Greek Chicken Stuffed Zucchini', 'Zucchini');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (80, 'Greek Chicken Stuffed Zucchini', 'Extra-virgin Olive Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (80, 'Greek Chicken Stuffed Zucchini', 'Onion');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (80, 'Greek Chicken Stuffed Zucchini', 'Garlic');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (80, 'Greek Chicken Stuffed Zucchini', 'Chicken');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (80, 'Greek Chicken Stuffed Zucchini', 'Oregano');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (80, 'Greek Chicken Stuffed Zucchini', 'Kosher Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (80, 'Greek Chicken Stuffed Zucchini', 'Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (80, 'Greek Chicken Stuffed Zucchini', 'Chickpeas');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (80, 'Greek Chicken Stuffed Zucchini', 'Tomato');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (80, 'Greek Chicken Stuffed Zucchini', 'Kalamata Olives');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (80, 'Greek Chicken Stuffed Zucchini', 'Feta Cheese');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (80, 'Greek Chicken Stuffed Zucchini', 'Lemon');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (80, 'Greek Chicken Stuffed Zucchini', 'Cucumber');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (80, 'Greek Chicken Stuffed Zucchini', 'Dill');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (81, 'Caprese Chicken', 'Extra-virgin Olive Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (81, 'Caprese Chicken', 'Chicken');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (81, 'Caprese Chicken', 'Kosher Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (81, 'Caprese Chicken', 'Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (81, 'Caprese Chicken', 'Balsamic Vinegar');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (81, 'Caprese Chicken', 'Garlic');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (81, 'Caprese Chicken', 'Tomato');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (81, 'Caprese Chicken', 'Basil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (81, 'Caprese Chicken', 'Mozzarella Balls');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (82, 'Hunan Chicken', 'Canola Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (82, 'Hunan Chicken', 'Chicken');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (82, 'Hunan Chicken', 'Ginger');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (82, 'Hunan Chicken', 'Broccoli');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (82, 'Hunan Chicken', 'Red Bell Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (82, 'Hunan Chicken', 'Chilis');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (82, 'Hunan Chicken', 'Sherry Vinegar');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (82, 'Hunan Chicken', 'Soy Sauce');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (82, 'Hunan Chicken', 'Cornstarch');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (82, 'Hunan Chicken', 'Sambal Oelek');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (82, 'Hunan Chicken', 'Sesame Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (82, 'Hunan Chicken', 'Rice');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (83, 'Pineapple Chicken', 'Vegetable Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (83, 'Pineapple Chicken', 'Chicken');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (83, 'Pineapple Chicken', 'Kosher Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (83, 'Pineapple Chicken', 'Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (83, 'Pineapple Chicken', 'Pineapple Juice');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (83, 'Pineapple Chicken', 'Soy Sauce');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (83, 'Pineapple Chicken', 'Brown Sugar');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (83, 'Pineapple Chicken', 'Hoisin Sauce');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (83, 'Pineapple Chicken', 'Garlic');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (83, 'Pineapple Chicken', 'Jalapeno');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (83, 'Pineapple Chicken', 'Cornstarch');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (83, 'Pineapple Chicken', 'Pineapple');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (83, 'Pineapple Chicken', 'Cashews');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (83, 'Pineapple Chicken', 'Green Onions');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (83, 'Pineapple Chicken', 'Rice');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (83, 'Pineapple Chicken', 'Lime');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (84, 'Honey Balsamic Grilled Chicken Thighs', 'Chicken');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (84, 'Honey Balsamic Grilled Chicken Thighs', 'Kosher Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (84, 'Honey Balsamic Grilled Chicken Thighs', 'Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (84, 'Honey Balsamic Grilled Chicken Thighs', 'Salted Butter');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (84, 'Honey Balsamic Grilled Chicken Thighs', 'Balsamic Vinegar');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (84, 'Honey Balsamic Grilled Chicken Thighs', 'Honey');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (84, 'Honey Balsamic Grilled Chicken Thighs', 'Garlic');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (84, 'Honey Balsamic Grilled Chicken Thighs', 'Canola Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (84, 'Honey Balsamic Grilled Chicken Thighs', 'Chives');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (84, 'Honey Balsamic Grilled Chicken Thighs', 'Parsley');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (84, 'Honey Balsamic Grilled Chicken Thighs', 'Lemon');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (85, 'Popcorn Chicken', 'Chicken');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (85, 'Popcorn Chicken', 'Kosher Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (85, 'Popcorn Chicken', 'Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (85, 'Popcorn Chicken', 'Extra-virgin Olive Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (85, 'Popcorn Chicken', 'Corn Flakes');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (85, 'Popcorn Chicken', 'Olive Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (85, 'Popcorn Chicken', 'Mayonnaise');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (85, 'Popcorn Chicken', 'Sour Cream');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (85, 'Popcorn Chicken', 'Hot Sauce');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (85, 'Popcorn Chicken', 'Cayenne Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (85, 'Popcorn Chicken', 'Green Onions');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (86, 'Chicken Parm Dippers', 'Chicken');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (86, 'Chicken Parm Dippers', 'Kosher Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (86, 'Chicken Parm Dippers', 'Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (86, 'Chicken Parm Dippers', 'Breadcrumbs');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (86, 'Chicken Parm Dippers', 'Oregano');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (86, 'Chicken Parm Dippers', 'Garlic Powder');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (86, 'Chicken Parm Dippers', 'Parmesan cheese');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (86, 'Chicken Parm Dippers', 'Egg');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (86, 'Chicken Parm Dippers', 'All Purpose Flour');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (86, 'Chicken Parm Dippers', 'Canola Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (86, 'Chicken Parm Dippers', 'Mozzarella Balls');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (86, 'Chicken Parm Dippers', 'Tomato Sauce');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (86, 'Chicken Parm Dippers', 'Basil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (87, 'Sheet Pan Shrimp Boil', 'Potato');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (87, 'Sheet Pan Shrimp Boil', 'Shrimp');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (87, 'Sheet Pan Shrimp Boil', 'Corn');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (87, 'Sheet Pan Shrimp Boil', 'Andouille Sausage');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (87, 'Sheet Pan Shrimp Boil', 'Lemon');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (87, 'Sheet Pan Shrimp Boil', 'Garlic Powder');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (87, 'Sheet Pan Shrimp Boil', 'Old Bay Seasoning');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (87, 'Sheet Pan Shrimp Boil', 'Salted Butter');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (87, 'Sheet Pan Shrimp Boil', 'Extra-virgin Olive Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (87, 'Sheet Pan Shrimp Boil', 'Kosher Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (87, 'Sheet Pan Shrimp Boil', 'Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (87, 'Sheet Pan Shrimp Boil', 'Parsley');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (87, 'Sheet Pan Shrimp Boil', 'Mayonnaise');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (87, 'Sheet Pan Shrimp Boil', 'Chives');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (87, 'Sheet Pan Shrimp Boil', 'Dijon Mustard');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (87, 'Sheet Pan Shrimp Boil', 'Lemon Zest');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (88, 'Spanish Noodles with Shrimp and Peas', 'Seafood Stock');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (88, 'Spanish Noodles with Shrimp and Peas', 'Clam Broth');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (88, 'Spanish Noodles with Shrimp and Peas', 'Tomato Paste');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (88, 'Spanish Noodles with Shrimp and Peas', 'Olive Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (88, 'Spanish Noodles with Shrimp and Peas', 'Fidelini Noodles');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (88, 'Spanish Noodles with Shrimp and Peas', 'Red Peppers');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (88, 'Spanish Noodles with Shrimp and Peas', 'Garlic');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (88, 'Spanish Noodles with Shrimp and Peas', 'Paprika');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (88, 'Spanish Noodles with Shrimp and Peas', 'Peas');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (88, 'Spanish Noodles with Shrimp and Peas', 'Shrimp');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (88, 'Spanish Noodles with Shrimp and Peas', 'Parsley');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (88, 'Spanish Noodles with Shrimp and Peas', 'Lemon');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (89, 'French Onion Soup', 'Salted Butter');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (89, 'French Onion Soup', 'Onion');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (89, 'French Onion Soup', 'All Purpose Flour');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (89, 'French Onion Soup', 'Kosher Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (89, 'French Onion Soup', 'Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (89, 'French Onion Soup', 'White wine');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (89, 'French Onion Soup', 'Chicken Stock');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (89, 'French Onion Soup', 'Beef Stock');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (89, 'French Onion Soup', 'Thyme');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (89, 'French Onion Soup', 'Baguette Bread');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (90, 'Garlicky Lemon Baked Tilapia', 'Tilapia Fillets');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (90, 'Garlicky Lemon Baked Tilapia', 'Kosher Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (90, 'Garlicky Lemon Baked Tilapia', 'Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (90, 'Garlicky Lemon Baked Tilapia', 'Salted Butter');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (90, 'Garlicky Lemon Baked Tilapia', 'Garlic');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (90, 'Garlicky Lemon Baked Tilapia', 'Red Pepper Flakes');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (90, 'Garlicky Lemon Baked Tilapia', 'Lemon');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (90, 'Garlicky Lemon Baked Tilapia', 'Lemon juice');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (90, 'Garlicky Lemon Baked Tilapia', 'Lemon Zest');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (91, 'Lemon Pepper Chicken', 'All Purpose Flour');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (91, 'Lemon Pepper Chicken', 'Lemon Pepper Seasoning');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (91, 'Lemon Pepper Chicken', 'Kosher Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (91, 'Lemon Pepper Chicken', 'Lemon');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (91, 'Lemon Pepper Chicken', 'Chicken');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (91, 'Lemon Pepper Chicken', 'Extra-virgin Olive Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (91, 'Lemon Pepper Chicken', 'Chicken Broth');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (91, 'Lemon Pepper Chicken', 'Salted Butter');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (91, 'Lemon Pepper Chicken', 'Garlic');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (91, 'Lemon Pepper Chicken', 'Parsley');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (92, 'Chicken Fajitas', 'Extra-virgin Olive Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (92, 'Chicken Fajitas', 'Lime');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (92, 'Chicken Fajitas', 'Cumin');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (92, 'Chicken Fajitas', 'Red Pepper Flakes');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (92, 'Chicken Fajitas', 'Chicken');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (92, 'Chicken Fajitas', 'Kosher Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (92, 'Chicken Fajitas', 'Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (92, 'Chicken Fajitas', 'Red Bell Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (92, 'Chicken Fajitas', 'Onion');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (92, 'Chicken Fajitas', 'Corn Tortillas');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (93, 'Swedish Meatballs and Mashed Potatoes', 'Potato');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (93, 'Swedish Meatballs and Mashed Potatoes', 'Salted Butter');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (93, 'Swedish Meatballs and Mashed Potatoes', 'Heavy cream');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (93, 'Swedish Meatballs and Mashed Potatoes', 'Kosher Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (93, 'Swedish Meatballs and Mashed Potatoes', 'Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (93, 'Swedish Meatballs and Mashed Potatoes', 'Breadcrumbs');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (93, 'Swedish Meatballs and Mashed Potatoes', 'Whole Milk');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (93, 'Swedish Meatballs and Mashed Potatoes', 'Onion');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (93, 'Swedish Meatballs and Mashed Potatoes', 'Garlic');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (93, 'Swedish Meatballs and Mashed Potatoes', 'Ground Beef');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (93, 'Swedish Meatballs and Mashed Potatoes', 'Ground Pork');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (93, 'Swedish Meatballs and Mashed Potatoes', 'Egg');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (93, 'Swedish Meatballs and Mashed Potatoes', 'Allspice');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (93, 'Swedish Meatballs and Mashed Potatoes', 'Nutmeg');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (93, 'Swedish Meatballs and Mashed Potatoes', 'All Purpose Flour');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (93, 'Swedish Meatballs and Mashed Potatoes', 'Beef Broth');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (93, 'Swedish Meatballs and Mashed Potatoes', 'Chives');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (94, 'Melted Snowman Cookies', 'Sugar Cookies');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (94, 'Melted Snowman Cookies', 'Marshmallows');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (94, 'Melted Snowman Cookies', 'Icing');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (94, 'Melted Snowman Cookies', 'Orange Jimmies');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (95, 'Shrimp Enchiladas', 'Extra-virgin Olive Oil');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (95, 'Shrimp Enchiladas', 'Garlic');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (95, 'Shrimp Enchiladas', 'Onion');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (95, 'Shrimp Enchiladas', 'Red Bell Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (95, 'Shrimp Enchiladas', 'Jalapeno');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (95, 'Shrimp Enchiladas', 'Shrimp');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (95, 'Shrimp Enchiladas', 'Kosher Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (95, 'Shrimp Enchiladas', 'Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (95, 'Shrimp Enchiladas', 'Salted Butter');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (95, 'Shrimp Enchiladas', 'All Purpose Flour');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (95, 'Shrimp Enchiladas', 'Milk');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (95, 'Shrimp Enchiladas', 'Sour Cream');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (95, 'Shrimp Enchiladas', 'Chilis');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (95, 'Shrimp Enchiladas', 'Cumin');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (95, 'Shrimp Enchiladas', 'Flour Tortillas');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (95, 'Shrimp Enchiladas', 'Monterey Jack Cheese');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (95, 'Shrimp Enchiladas', 'Cilantro');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (95, 'Shrimp Enchiladas', 'Pico de gallo');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (96, 'Mussels with Tomatoes and Garlic', 'Salted Butter');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (96, 'Mussels with Tomatoes and Garlic', 'Onion');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (96, 'Mussels with Tomatoes and Garlic', 'Garlic');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (96, 'Mussels with Tomatoes and Garlic', 'Tomato');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (96, 'Mussels with Tomatoes and Garlic', 'White wine');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (96, 'Mussels with Tomatoes and Garlic', 'Parsley');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (96, 'Mussels with Tomatoes and Garlic', 'Kosher Salt');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (96, 'Mussels with Tomatoes and Garlic', 'Pepper');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (96, 'Mussels with Tomatoes and Garlic', 'Mussels');
INSERT INTO lewischr_recipes.recipe_ingredient_join (rID, title, ingredient) VALUES (96, 'Mussels with Tomatoes and Garlic', 'Bread');