INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (5, 'Oven Roasted Potato ''Fries''', 'Appetizer');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (37, 'Chili', 'Appetizer');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (40, 'Chicken Noodle Soup', 'Appetizer');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (41, 'Chicken Wings', 'Appetizer');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (45, 'Beef Stew', 'Appetizer');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (52, 'Corn on the Cob', 'Appetizer');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (55, 'French Bread', 'Appetizer');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (69, 'Greek Salad', 'Appetizer');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (74, 'Mediterranean Salad with Lemon-Herb Vinaigrette', 'Appetizer');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (75, 'Steak Salad', 'Appetizer');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (76, 'Sesame Ginger Salmon Salad', 'Appetizer');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (85, 'Popcorn Chicken', 'Appetizer');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (86, 'Chicken Parm Dippers', 'Appetizer');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (93, 'Swedish Meatballs and Mashed Potatoes', 'Appetizer');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (13, 'Spinach and Red Pepper Frittata', 'Breakfast');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (31, 'French Toast', 'Breakfast');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (13, 'Spinach and Red Pepper Frittata', 'Brunch');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (31, 'French Toast', 'Brunch');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (14, 'Sweet Potato Meringue Pie', 'Dessert');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (34, 'Ginger Bread Cookies', 'Dessert');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (39, 'Brownies', 'Dessert');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (48, 'Sweet Potato Pie', 'Dessert');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (49, 'Bacardi Rum Cake', 'Dessert');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (56, 'Marbled Brownies', 'Dessert');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (57, 'Cookies N Cream Fudge', 'Dessert');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (77, 'Peppermint Bark', 'Dessert');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (1, 'Pizza', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (2, 'Pesto Pasta', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (3, 'Shrimp Fried Rice', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (4, 'Creamy Homemade Baked Mac and Cheese', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (5, 'Oven Roasted Potato ''Fries''', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (11, 'Roasted Salmon Glazed With Brown Sugar and Mustard', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (12, 'Spaghetti al Limone', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (33, 'Mac & Cheese', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (35, 'Italian Meatballs', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (36, 'Fried Rice', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (37, 'Chili', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (38, 'Chicken Parmesan', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (40, 'Chicken Noodle Soup', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (41, 'Chicken Wings', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (42, 'Baked Salmon', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (44, 'Fried Chicken', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (45, 'Beef Stew', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (46, 'Sesame Chicken', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (50, 'Sloppy Joes', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (51, 'Lemon Baked Cod', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (52, 'Corn on the Cob', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (53, 'Flat Iron Steak', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (54, 'Teriyaki Pork Chops', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (58, 'Corned Beef and Cabbage', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (60, 'Tofu Stir Fry', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (62, 'Shrimp and Broccoli Fettuccini', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (63, 'Coconut Shrimp with Spicy Honey', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (64, 'Corn Bread Chili Pie', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (66, 'Beef Stroganoff', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (68, 'Chicken Chow Mein', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (70, 'Chimichurri Grilled Steak', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (73, 'Steak Frites', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (74, 'Mediterranean Salad with Lemon-Herb Vinaigrette', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (75, 'Steak Salad', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (76, 'Sesame Ginger Salmon Salad', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (78, 'Baked Swordfish Steak', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (79, 'Shrimp Fajitas', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (80, 'Greek Chicken Stuffed Zucchini', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (81, 'Caprese Chicken', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (82, 'Hunan Chicken', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (83, 'Pineapple Chicken', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (84, 'Honey Balsamic Grilled Chicken Thighs', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (85, 'Popcorn Chicken', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (86, 'Chicken Parm Dippers', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (87, 'Sheet Pan Shrimp Boil', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (88, 'Spanish Noodles with Shrimp and Peas', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (90, 'Garlicky Lemon Baked Tilapia', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (91, 'Lemon Pepper Chicken', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (92, 'Chicken Fajitas', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (93, 'Swedish Meatballs and Mashed Potatoes', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (96, 'Mussels with Tomatoes and Garlic', 'Dinner');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (2, 'Pesto Pasta', 'Easy');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (3, 'Shrimp Fried Rice', 'Easy');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (5, 'Oven Roasted Potato ''Fries''', 'Easy');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (12, 'Spaghetti al Limone', 'Easy');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (31, 'French Toast', 'Easy');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (36, 'Fried Rice', 'Easy');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (52, 'Corn on the Cob', 'Easy');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (54, 'Teriyaki Pork Chops', 'Easy');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (59, 'Sweet Potato Chips', 'Easy');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (60, 'Tofu Stir Fry', 'Easy');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (11, 'Roasted Salmon Glazed With Brown Sugar and Mustard', 'For One');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (12, 'Spaghetti al Limone', 'For One');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (13, 'Spinach and Red Pepper Frittata', 'For One');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (1, 'Pizza', 'For Two');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (12, 'Spaghetti al Limone', 'For Two');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (13, 'Spinach and Red Pepper Frittata', 'For Two');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (42, 'Baked Salmon', 'For Two');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (43, 'Garlic Shrimp', 'For Two');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (3, 'Shrimp Fried Rice', 'Lunch');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (4, 'Creamy Homemade Baked Mac and Cheese', 'Lunch');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (5, 'Oven Roasted Potato ''Fries''', 'Lunch');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (12, 'Spaghetti al Limone', 'Lunch');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (33, 'Mac & Cheese', 'Lunch');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (37, 'Chili', 'Lunch');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (40, 'Chicken Noodle Soup', 'Lunch');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (41, 'Chicken Wings', 'Lunch');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (50, 'Sloppy Joes', 'Lunch');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (67, 'Reuben Sandwich', 'Lunch');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (68, 'Chicken Chow Mein', 'Lunch');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (95, 'Shrimp Enchiladas', 'Lunch');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (3, 'Shrimp Fried Rice', 'Main Course');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (4, 'Creamy Homemade Baked Mac and Cheese', 'Main Course');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (11, 'Roasted Salmon Glazed With Brown Sugar and Mustard', 'Main Course');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (12, 'Spaghetti al Limone', 'Main Course');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (33, 'Mac & Cheese', 'Main Course');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (35, 'Italian Meatballs', 'Main Course');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (37, 'Chili', 'Main Course');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (38, 'Chicken Parmesan', 'Main Course');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (41, 'Chicken Wings', 'Main Course');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (42, 'Baked Salmon', 'Main Course');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (43, 'Garlic Shrimp', 'Main Course');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (44, 'Fried Chicken', 'Main Course');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (45, 'Beef Stew', 'Main Course');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (46, 'Sesame Chicken', 'Main Course');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (50, 'Sloppy Joes', 'Main Course');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (51, 'Lemon Baked Cod', 'Main Course');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (53, 'Flat Iron Steak', 'Main Course');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (54, 'Teriyaki Pork Chops', 'Main Course');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (58, 'Corned Beef and Cabbage', 'Main Course');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (60, 'Tofu Stir Fry', 'Main Course');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (62, 'Shrimp and Broccoli Fettuccini', 'Main Course');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (63, 'Coconut Shrimp with Spicy Honey', 'Main Course');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (64, 'Corn Bread Chili Pie', 'Main Course');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (65, 'Bolognese Sauce', 'Main Course');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (66, 'Beef Stroganoff', 'Main Course');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (68, 'Chicken Chow Mein', 'Main Course');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (70, 'Chimichurri Grilled Steak', 'Main Course');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (73, 'Steak Frites', 'Main Course');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (74, 'Mediterranean Salad with Lemon-Herb Vinaigrette', 'Main Course');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (78, 'Baked Swordfish Steak', 'Main Course');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (79, 'Shrimp Fajitas', 'Main Course');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (80, 'Greek Chicken Stuffed Zucchini', 'Main Course');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (81, 'Caprese Chicken', 'Main Course');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (82, 'Hunan Chicken', 'Main Course');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (83, 'Pineapple Chicken', 'Main Course');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (84, 'Honey Balsamic Grilled Chicken Thighs', 'Main Course');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (87, 'Sheet Pan Shrimp Boil', 'Main Course');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (88, 'Spanish Noodles with Shrimp and Peas', 'Main Course');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (90, 'Garlicky Lemon Baked Tilapia', 'Main Course');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (91, 'Lemon Pepper Chicken', 'Main Course');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (92, 'Chicken Fajitas', 'Main Course');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (95, 'Shrimp Enchiladas', 'Main Course');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (96, 'Mussels with Tomatoes and Garlic', 'Main Course');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (2, 'Pesto Pasta', 'Quick');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (11, 'Roasted Salmon Glazed With Brown Sugar and Mustard', 'Quick');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (12, 'Spaghetti al Limone', 'Quick');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (31, 'French Toast', 'Quick');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (36, 'Fried Rice', 'Quick');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (38, 'Chicken Parmesan', 'Quick');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (43, 'Garlic Shrimp', 'Quick');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (52, 'Corn on the Cob', 'Quick');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (4, 'Creamy Homemade Baked Mac and Cheese', 'Side Dish');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (3, 'Shrimp Fried Rice', 'Side Dish');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (5, 'Oven Roasted Potato ''Fries''', 'Side Dish');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (36, 'Fried Rice', 'Side Dish');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (47, 'Greek Potatoes', 'Side Dish');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (61, 'Shrimp Fried Rice', 'Side Dish');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (71, 'Swedish Meatballs and Mashed Potatoes', 'Side Dish');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (5, 'Oven Roasted Potato ''Fries''', 'Snack');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (34, 'Ginger Bread Cookies', 'Snack');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (36, 'Fried Rice', 'Snack');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (59, 'Sweet Potato Chips', 'Snack');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (4, 'Creamy Homemade Baked Mac and Cheese', 'Weekday');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (3, 'Shrimp Fried Rice', 'Weekday');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (5, 'Oven Roasted Potato ''Fries''', 'Weekday');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (11, 'Roasted Salmon Glazed With Brown Sugar and Mustard', 'Weekday');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (12, 'Spaghetti al Limone', 'Weekday');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (33, 'Mac & Cheese', 'Weekday');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (40, 'Chicken Noodle Soup', 'Weekday');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (41, 'Chicken Wings', 'Weekday');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (67, 'Reuben Sandwich', 'Weekday');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (68, 'Chicken Chow Mein', 'Weekday');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (95, 'Shrimp Enchiladas', 'Weekday');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (4, 'Creamy Homemade Baked Mac and Cheese', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (3, 'Shrimp Fried Rice', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (5, 'Oven Roasted Potato ''Fries''', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (11, 'Roasted Salmon Glazed With Brown Sugar and Mustard', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (12, 'Spaghetti al Limone', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (33, 'Mac & Cheese', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (34, 'Ginger Bread Cookies', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (35, 'Italian Meatballs', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (36, 'Fried Rice', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (38, 'Chicken Parmesan', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (39, 'Brownies', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (40, 'Chicken Noodle Soup', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (41, 'Chicken Wings', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (42, 'Baked Salmon', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (43, 'Garlic Shrimp', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (44, 'Fried Chicken', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (45, 'Beef Stew', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (46, 'Sesame Chicken', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (47, 'Greek Potatoes', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (48, 'Sweet Potato Pie', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (49, 'Bacardi Rum Cake', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (50, 'Sloppy Joes', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (51, 'Lemon Baked Cod', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (52, 'Corn on the Cob', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (53, 'Flat Iron Steak', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (54, 'Teriyaki Pork Chops', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (55, 'French Bread', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (56, 'Marbled Brownies', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (57, 'Cookies N Cream Fudge', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (58, 'Corned Beef and Cabbage', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (61, 'Shrimp Fried Rice', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (62, 'Shrimp and Broccoli Fettuccini', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (63, 'Coconut Shrimp with Spicy Honey', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (64, 'Corn Bread Chili Pie', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (65, 'Bolognese Sauce', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (66, 'Beef Stroganoff', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (68, 'Chicken Chow Mein', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (69, 'Greek Salad', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (70, 'Chimichurri Grilled Steak', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (71, 'Swedish Meatballs and Mashed Potatoes', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (73, 'Steak Frites', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (74, 'Mediterranean Salad with Lemon-Herb Vinaigrette', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (75, 'Steak Salad', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (76, 'Sesame Ginger Salmon Salad', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (77, 'Peppermint Bark', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (78, 'Baked Swordfish Steak', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (79, 'Shrimp Fajitas', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (80, 'Greek Chicken Stuffed Zucchini', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (81, 'Caprese Chicken', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (82, 'Hunan Chicken', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (83, 'Pineapple Chicken', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (84, 'Honey Balsamic Grilled Chicken Thighs', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (85, 'Popcorn Chicken', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (86, 'Chicken Parm Dippers', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (87, 'Sheet Pan Shrimp Boil', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (88, 'Spanish Noodles with Shrimp and Peas', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (90, 'Garlicky Lemon Baked Tilapia', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (91, 'Lemon Pepper Chicken', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (92, 'Chicken Fajitas', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (93, 'Swedish Meatballs and Mashed Potatoes', 'Weeknight');
INSERT INTO lewischr_recipes.recipe_meal_join (mID, title, meal) VALUES (96, 'Mussels with Tomatoes and Garlic', 'Weeknight');