INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (1, 'Tomato');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (2, 'Cheese');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (3, 'Bread');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (4, 'Penne');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (5, 'Tomato Sauce');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (6, 'Pesto');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (7, 'Garlic');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (8, 'Olive Oil');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (9, 'Shrimp');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (10, 'Egg');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (11, 'Ginger');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (12, 'Garlic');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (13, 'Scallions');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (14, 'Rice');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (15, 'Soy Sauce');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (16, 'Elbow Pasta');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (17, 'Unsalted Butter');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (18, 'Flour');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (19, 'All Purpose Flour');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (20, 'Whole Milk');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (21, 'Milk');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (22, 'Half and Half');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (23, 'Cheddar Cheese');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (24, 'Gruyere Cheese');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (25, 'Paprika');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (26, 'Potato');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (32, 'Salmon');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (33, 'Brown Sugar');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (34, 'Dijon Mustard');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (35, 'Lemon');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (36, 'White wine');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (37, 'Heavy cream');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (38, 'Spaghetti');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (39, 'Parmesan cheese');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (40, 'Salt');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (41, 'Pepper');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (42, 'Spinach');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (43, 'Red Peppers');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (44, 'Marjoram leaves');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (45, 'Banana');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (46, 'Pie Crust');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (47, 'Sugar');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (48, 'Vanilla extract');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (49, 'Sweet Potatoes');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (50, 'Cinnamon');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (51, 'Nutmeg');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (52, 'Dill');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (53, 'Orange');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (54, 'Apple');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (55, 'Chocolate Chips');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (56, 'Lemon juice');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (69, 'Salted Butter');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (70, 'Baking Powder');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (71, 'Baking Soda');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (72, 'Buttermilk');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (75, 'Plain Yogurt');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (76, 'Cucumber');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (77, 'Ground Beef');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (78, 'Onion');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (79, 'Oregano');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (80, 'Garlic Powder');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (81, 'Onion Powder');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (82, 'Pita Bread');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (83, 'Lettuce');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (84, 'Macaroni');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (85, 'Pork Roast');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (86, 'Ginger Ale');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (87, 'BBQ Sauce');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (88, 'Ground Cloves');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (89, 'Molasses');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (90, 'Lemon Zest');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (91, 'Breadcrumbs');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (92, 'Parsley');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (93, 'Oil');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (94, 'Sesame Oil');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (95, 'Chicken');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (96, 'Carrot');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (97, 'Peas');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (98, 'Green Onions');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (99, 'Bean Sprouts');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (100, 'Green Pepper');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (101, 'Jalapeno');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (102, 'Cumin');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (103, 'Chili Powder');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (104, 'Cayenne Pepper');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (105, 'Kidney Beans');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (106, 'Black Beans');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (107, 'Water');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (108, 'Vegetable Oil');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (109, 'Cocoa Powder');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (110, 'Celery');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (111, 'Thyme');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (112, 'Poultry Seasoning');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (113, 'Chicken Broth');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (114, 'Chicken Bouillon');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (115, 'Egg Noodle');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (116, 'Garlic Salt');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (117, 'Light Olive Oil');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (118, 'Basil');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (119, 'Worcestershire Sauce');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (120, 'Balsamic Vinegar');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (121, 'Yellow Mustard');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (122, 'Pork Ribs');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (123, 'Hickory Smoke Salt');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (124, 'Ground Red Pepper');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (125, 'Red Pepper Flakes');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (126, 'Steak Seasoning');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (127, 'Sour Cream');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (128, 'Hot Sauce');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (129, 'Beef Stew Meat');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (130, 'Beef Broth');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (131, 'Honey');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (132, 'Cornstarch');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (133, 'Sesame Seeds');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (134, 'Cream Cheese');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (135, 'Bacon');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (136, 'Italian Sausage');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (137, 'Sea Salt');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (138, 'Active Dry Yeast');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (139, 'Cornmeal');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (140, 'Evaporated Milk');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (141, 'Mashed Potatoes');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (142, 'Taco Seasoning');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (143, 'Pecans');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (144, 'Cake Mix');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (145, 'Vanilla Pudding');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (146, 'Rum');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (147, 'Skewers');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (148, 'Coriander');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (149, 'Garam Masala');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (150, 'Whipped Cream');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (151, 'Cilantro');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (152, 'Raisins');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (153, 'Oatmeal');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (154, 'Okra');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (155, 'Bay Leaves');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (156, 'Crab');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (157, 'Oyster');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (158, 'White Fish Fillet');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (159, 'Gumbo File Powder');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (160, 'Hamburger');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (161, 'Vinegar');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (162, 'Catsup');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (163, 'Steak');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (164, 'Broccoli');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (165, 'Poppy Seeds');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (166, 'Cod Fish Fillet');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (167, 'White Pepper');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (168, 'Corn');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (169, 'Flat Iron Steak');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (170, 'Italian Dressing');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (171, 'Pork Chops');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (172, 'Orange Juice');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (173, 'Brownie Mix');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (174, 'Powdered Sugar');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (175, 'Marshmallow Creme');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (176, 'Almond Bark');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (177, 'Oreos');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (178, 'Apple Cider Vinegar');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (179, 'Corned Beef Brisket');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (180, 'Cabbage');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (181, 'Blueberries');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (182, 'Ground Turkey');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (183, 'Yellow Onion');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (184, 'Romano Cheese');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (185, 'Ramen Noodles');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (186, 'Mixed Vegetables');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (187, 'Teriyaki Sauce');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (188, 'Tofu');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (189, 'Peanut Oil');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (190, 'Provolone Cheese');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (191, 'Mushrooms');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (192, 'Red Bell Pepper');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (193, 'Fettuccini');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (194, 'Extra-virgin Olive Oil');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (195, 'Unsweetened Shredded Coconut');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (196, 'Sourdough Bread');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (197, 'Ground Pork');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (198, 'Tomato Paste');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (199, 'Muffin Mix');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (200, 'Salsa');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (201, 'Fusili Pasta');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (202, 'Mozzarella Balls');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (203, 'Salami');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (204, 'Artichoke Hearts');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (205, 'Black Olives');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (206, 'Red Wine Vinegar');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (207, 'Italian Seasoning');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (208, 'Kosher Salt');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (209, 'Beef Chuck Roast');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (210, 'Rye Bread');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (211, 'Russian Dressing');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (212, 'Swiss Cheese');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (213, 'Sauerkraut');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (214, 'Chow Mein Noodles');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (215, 'Oyster Sauce');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (216, 'Kalamata Olives');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (217, 'Red Onion');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (218, 'Feta Cheese');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (219, 'Chives');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (220, 'Lime');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (221, 'Skirt Steak');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (222, 'Asparagus');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (223, 'Coconut Oil');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (224, 'Curry Powder');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (225, 'Coconut Milk');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (226, 'Chickpeas');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (227, 'White Bread');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (228, 'Allspice');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (229, 'Canola Oil');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (230, 'New York Strip Steak');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (231, 'Hazelnuts');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (232, 'Tilapia Fillets');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (233, 'Zucchini');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (234, 'Mint Leaves');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (235, 'Squash');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (236, 'Flank Steak');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (237, 'Sherry Vinegar');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (238, 'Blue Cheese');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (239, 'White Vinegar');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (240, 'Wonton Wrappers');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (241, 'Mixed Greens');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (242, 'Cherries');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (243, 'Radicchio');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (244, 'Semisweet Chocolate');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (245, 'White Chocolate');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (246, 'Peppermint Extract');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (247, 'Candy Canes');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (248, 'Swordfish Steaks');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (249, 'Corn Tortillas');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (250, 'Cotija');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (251, 'Angel Hair');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (252, 'Caesar Dressing');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (253, 'Chilis');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (254, 'Sambal Oelek');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (255, 'Pineapple Juice');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (256, 'Hoisin Sauce');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (257, 'Pineapple');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (258, 'Cashews');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (259, 'Corn Flakes');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (260, 'Mayonnaise');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (261, 'Andouille Sausage');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (262, 'Old Bay Seasoning');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (263, 'Seafood Stock');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (264, 'Clam Broth');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (265, 'Fidelini Noodles');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (266, 'Chicken Stock');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (267, 'Beef Stock');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (268, 'Baguette Bread');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (269, 'Halibut Steaks');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (270, 'Mango');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (271, 'Salmon Fillets');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (272, 'Corn Tostadas');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (273, 'Avocado');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (274, 'Lemon Pepper Seasoning');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (275, 'Rosemary');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (276, 'Shallots');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (277, 'Lime Zest');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (278, 'Udon Noodles');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (279, 'Chili Peppers');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (280, '');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (281, 'Sugar Cookies');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (282, 'Marshmallows');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (283, 'Icing');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (284, 'Orange Jimmies');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (285, 'Chocolate Jimmies');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (286, 'Flour Tortillas');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (287, 'Monterey Jack Cheese');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (288, 'Pico de gallo');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (289, 'Mussels');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (290, 'Ground Chicken');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (291, 'Ground Chicken');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (292, 'Ground Chicken');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (293, 'Tuna');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (294, 'Seaweed');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (295, 'Mangom');
INSERT INTO lewischr_recipes.ingredients (ID, ingredient) VALUES (296, 'Eggplant');