INSERT INTO lewischr_recipes.diets (ID, diet) VALUES (1, 'Dairy-Free');
INSERT INTO lewischr_recipes.diets (ID, diet) VALUES (2, 'Gluten-Free');
INSERT INTO lewischr_recipes.diets (ID, diet) VALUES (3, 'Halal');
INSERT INTO lewischr_recipes.diets (ID, diet) VALUES (4, 'Healthy');
INSERT INTO lewischr_recipes.diets (ID, diet) VALUES (5, 'High Fiber');
INSERT INTO lewischr_recipes.diets (ID, diet) VALUES (6, 'High Protein');
INSERT INTO lewischr_recipes.diets (ID, diet) VALUES (7, 'Kosher');
INSERT INTO lewischr_recipes.diets (ID, diet) VALUES (8, 'Low Calorie');
INSERT INTO lewischr_recipes.diets (ID, diet) VALUES (9, 'Low Cholesterol');
INSERT INTO lewischr_recipes.diets (ID, diet) VALUES (10, 'Low Sugar');
INSERT INTO lewischr_recipes.diets (ID, diet) VALUES (11, 'Low-Carb');
INSERT INTO lewischr_recipes.diets (ID, diet) VALUES (12, 'Low-Fat');
INSERT INTO lewischr_recipes.diets (ID, diet) VALUES (13, 'Low-Sodium');
INSERT INTO lewischr_recipes.diets (ID, diet) VALUES (14, 'Nut-Free');
INSERT INTO lewischr_recipes.diets (ID, diet) VALUES (15, 'Paleo');
INSERT INTO lewischr_recipes.diets (ID, diet) VALUES (16, 'Raw');
INSERT INTO lewischr_recipes.diets (ID, diet) VALUES (17, 'Vegan');
INSERT INTO lewischr_recipes.diets (ID, diet) VALUES (18, 'Vegetarian');
INSERT INTO lewischr_recipes.diets (ID, diet) VALUES (19, 'Pescatarian');
INSERT INTO lewischr_recipes.diets (ID, diet) VALUES (20, 'Keto');