INSERT INTO lewischr_recipes.meals (ID, meal_type) VALUES (1, 'Appetizer');
INSERT INTO lewischr_recipes.meals (ID, meal_type) VALUES (2, 'Breakfast');
INSERT INTO lewischr_recipes.meals (ID, meal_type) VALUES (3, 'Brunch');
INSERT INTO lewischr_recipes.meals (ID, meal_type) VALUES (4, 'Dessert');
INSERT INTO lewischr_recipes.meals (ID, meal_type) VALUES (5, 'Dinner');
INSERT INTO lewischr_recipes.meals (ID, meal_type) VALUES (6, 'Easy');
INSERT INTO lewischr_recipes.meals (ID, meal_type) VALUES (7, 'For One');
INSERT INTO lewischr_recipes.meals (ID, meal_type) VALUES (8, 'For Two');
INSERT INTO lewischr_recipes.meals (ID, meal_type) VALUES (9, 'Lunch');
INSERT INTO lewischr_recipes.meals (ID, meal_type) VALUES (10, 'Main Course');
INSERT INTO lewischr_recipes.meals (ID, meal_type) VALUES (11, 'Quick');
INSERT INTO lewischr_recipes.meals (ID, meal_type) VALUES (12, 'Side Dish');
INSERT INTO lewischr_recipes.meals (ID, meal_type) VALUES (13, 'Snack');
INSERT INTO lewischr_recipes.meals (ID, meal_type) VALUES (14, 'Weekday');
INSERT INTO lewischr_recipes.meals (ID, meal_type) VALUES (15, 'Weeknight');