INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (2, 'Pesto Pasta', 'Dairy-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (3, 'Shrimp Fried Rice', 'Dairy-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (5, 'Oven Roasted Potato ''Fries''', 'Dairy-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (3, 'Shrimp Fried Rice', 'Gluten-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (5, 'Oven Roasted Potato ''Fries''', 'Gluten-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (11, 'Roasted Salmon Glazed With Brown Sugar and Mustard', 'Gluten-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (13, 'Spinach and Red Pepper Frittata', 'Gluten-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (52, 'Corn on the Cob', 'Gluten-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (2, 'Pesto Pasta', 'Healthy');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (3, 'Shrimp Fried Rice', 'Healthy');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (5, 'Oven Roasted Potato ''Fries''', 'Healthy');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (11, 'Roasted Salmon Glazed With Brown Sugar and Mustard', 'Healthy');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (12, 'Spaghetti al Limone', 'Healthy');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (13, 'Spinach and Red Pepper Frittata', 'Healthy');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (52, 'Corn on the Cob', 'Healthy');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (55, 'French Bread', 'Healthy');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (59, 'Sweet Potato Chips', 'Healthy');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (69, 'Greek Salad', 'Healthy');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (74, 'Mediterranean Salad with Lemon-Herb Vinaigrette', 'Healthy');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (75, 'Steak Salad', 'Healthy');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (76, 'Sesame Ginger Salmon Salad', 'Healthy');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (80, 'Greek Chicken Stuffed Zucchini', 'Healthy');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (13, 'Spinach and Red Pepper Frittata', 'High Fiber');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (13, 'Spinach and Red Pepper Frittata', 'High Protein');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (35, 'Italian Meatballs', 'High Protein');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (37, 'Chili', 'High Protein');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (41, 'Chicken Wings', 'High Protein');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (42, 'Baked Salmon', 'High Protein');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (44, 'Fried Chicken', 'High Protein');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (46, 'Sesame Chicken', 'High Protein');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (50, 'Sloppy Joes', 'High Protein');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (53, 'Flat Iron Steak', 'High Protein');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (54, 'Teriyaki Pork Chops', 'High Protein');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (64, 'Corn Bread Chili Pie', 'High Protein');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (65, 'Bolognese Sauce', 'High Protein');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (66, 'Beef Stroganoff', 'High Protein');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (67, 'Reuben Sandwich', 'High Protein');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (70, 'Chimichurri Grilled Steak', 'High Protein');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (73, 'Steak Frites', 'High Protein');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (78, 'Baked Swordfish Steak', 'High Protein');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (81, 'Caprese Chicken', 'High Protein');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (84, 'Honey Balsamic Grilled Chicken Thighs', 'High Protein');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (91, 'Lemon Pepper Chicken', 'High Protein');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (67, 'Reuben Sandwich', 'Kosher');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (5, 'Oven Roasted Potato ''Fries''', 'Low Cholesterol');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (40, 'Chicken Noodle Soup', 'Low Cholesterol');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (45, 'Beef Stew', 'Low Cholesterol');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (59, 'Sweet Potato Chips', 'Low Cholesterol');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (5, 'Oven Roasted Potato ''Fries''', 'Low Sugar');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (12, 'Spaghetti al Limone', 'Low Sugar');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (5, 'Oven Roasted Potato ''Fries''', 'Low-Fat');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (59, 'Sweet Potato Chips', 'Low-Fat');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (4, 'Creamy Homemade Baked Mac and Cheese', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (5, 'Oven Roasted Potato ''Fries''', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (11, 'Roasted Salmon Glazed With Brown Sugar and Mustard', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (12, 'Spaghetti al Limone', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (13, 'Spinach and Red Pepper Frittata', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (14, 'Sweet Potato Meringue Pie', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (31, 'French Toast', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (33, 'Mac & Cheese', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (34, 'Ginger Bread Cookies', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (35, 'Italian Meatballs', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (36, 'Fried Rice', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (37, 'Chili', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (38, 'Chicken Parmesan', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (39, 'Brownies', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (40, 'Chicken Noodle Soup', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (41, 'Chicken Wings', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (42, 'Baked Salmon', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (43, 'Garlic Shrimp', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (44, 'Fried Chicken', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (45, 'Beef Stew', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (46, 'Sesame Chicken', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (47, 'Greek Potatoes', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (48, 'Sweet Potato Pie', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (50, 'Sloppy Joes', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (51, 'Lemon Baked Cod', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (52, 'Corn on the Cob', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (53, 'Flat Iron Steak', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (54, 'Teriyaki Pork Chops', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (55, 'French Bread', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (56, 'Marbled Brownies', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (58, 'Corned Beef and Cabbage', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (59, 'Sweet Potato Chips', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (61, 'Shrimp Fried Rice', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (62, 'Shrimp and Broccoli Fettuccini', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (63, 'Coconut Shrimp with Spicy Honey', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (64, 'Corn Bread Chili Pie', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (65, 'Bolognese Sauce', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (66, 'Beef Stroganoff', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (67, 'Reuben Sandwich', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (68, 'Chicken Chow Mein', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (69, 'Greek Salad', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (70, 'Chimichurri Grilled Steak', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (71, 'Swedish Meatballs and Mashed Potatoes', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (76, 'Sesame Ginger Salmon Salad', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (78, 'Baked Swordfish Steak', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (79, 'Shrimp Fajitas', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (80, 'Greek Chicken Stuffed Zucchini', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (81, 'Caprese Chicken', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (82, 'Hunan Chicken', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (84, 'Honey Balsamic Grilled Chicken Thighs', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (85, 'Popcorn Chicken', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (86, 'Chicken Parm Dippers', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (87, 'Sheet Pan Shrimp Boil', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (88, 'Spanish Noodles with Shrimp and Peas', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (90, 'Garlicky Lemon Baked Tilapia', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (91, 'Lemon Pepper Chicken', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (92, 'Chicken Fajitas', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (93, 'Swedish Meatballs and Mashed Potatoes', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (95, 'Shrimp Enchiladas', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (96, 'Mussels with Tomatoes and Garlic', 'Nut-Free');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (5, 'Oven Roasted Potato ''Fries''', 'Paleo');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (14, 'Sweet Potato Meringue Pie', 'Paleo');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (52, 'Corn on the Cob', 'Paleo');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (5, 'Oven Roasted Potato ''Fries''', 'Vegan');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (52, 'Corn on the Cob', 'Vegan');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (60, 'Tofu Stir Fry', 'Vegan');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (69, 'Greek Salad', 'Vegan');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (73, 'Steak Frites', 'Vegan');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (74, 'Mediterranean Salad with Lemon-Herb Vinaigrette', 'Vegan');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (1, 'Pizza', 'Vegetarian');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (2, 'Pesto Pasta', 'Vegetarian');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (4, 'Creamy Homemade Baked Mac and Cheese', 'Vegetarian');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (5, 'Oven Roasted Potato ''Fries''', 'Vegetarian');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (12, 'Spaghetti al Limone', 'Vegetarian');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (13, 'Spinach and Red Pepper Frittata', 'Vegetarian');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (14, 'Sweet Potato Meringue Pie', 'Vegetarian');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (31, 'French Toast', 'Vegetarian');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (33, 'Mac & Cheese', 'Vegetarian');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (34, 'Ginger Bread Cookies', 'Vegetarian');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (39, 'Brownies', 'Vegetarian');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (47, 'Greek Potatoes', 'Vegetarian');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (52, 'Corn on the Cob', 'Vegetarian');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (60, 'Tofu Stir Fry', 'Vegetarian');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (69, 'Greek Salad', 'Vegetarian');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (74, 'Mediterranean Salad with Lemon-Herb Vinaigrette', 'Vegetarian');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (5, 'Oven Roasted Potato ''Fries''', 'Pescatarian');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (11, 'Roasted Salmon Glazed With Brown Sugar and Mustard', 'Pescatarian');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (12, 'Spaghetti al Limone', 'Pescatarian');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (13, 'Spinach and Red Pepper Frittata', 'Pescatarian');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (14, 'Sweet Potato Meringue Pie', 'Pescatarian');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (31, 'French Toast', 'Pescatarian');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (33, 'Mac & Cheese', 'Pescatarian');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (34, 'Ginger Bread Cookies', 'Pescatarian');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (39, 'Brownies', 'Pescatarian');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (42, 'Baked Salmon', 'Pescatarian');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (47, 'Greek Potatoes', 'Pescatarian');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (51, 'Lemon Baked Cod', 'Pescatarian');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (52, 'Corn on the Cob', 'Pescatarian');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (60, 'Tofu Stir Fry', 'Pescatarian');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (62, 'Shrimp and Broccoli Fettuccini', 'Pescatarian');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (69, 'Greek Salad', 'Pescatarian');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (74, 'Mediterranean Salad with Lemon-Herb Vinaigrette', 'Pescatarian');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (76, 'Sesame Ginger Salmon Salad', 'Pescatarian');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (78, 'Baked Swordfish Steak', 'Pescatarian');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (79, 'Shrimp Fajitas', 'Pescatarian');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (88, 'Spanish Noodles with Shrimp and Peas', 'Pescatarian');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (90, 'Garlicky Lemon Baked Tilapia', 'Pescatarian');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (95, 'Shrimp Enchiladas', 'Pescatarian');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (96, 'Mussels with Tomatoes and Garlic', 'Pescatarian');
INSERT INTO lewischr_recipes.recipe_diet_join (dID, title, diet) VALUES (13, 'Spinach and Red Pepper Frittata', 'Keto');